name:                bishop
version:             0.1.0.0
github:              "johnchandlerburnham/bishop"
license:             AGPL-3
author:              "John C. Burnham"
maintainer:          "jcb@johnchandlerburnham.com"
copyright:           "2020 John Burnham"


extra-source-files:
- README.md
- LICENSE

description:         Please see the README on GitHub at <https://github.com/johnchandlerburnham/bishop#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Language.Bishop.Net
    - Language.Bishop.Term
    - Language.Bishop.Parse
    - Language.Bishop.Eval

  dependencies:
    - megaparsec
    - containers
    - transformers
    - mtl
    - text
    - vector
    - unsafeperformst
    - cborg
    - serialise
    - ipld-cid
    - multibase
    - bytestring
    - cryptonite
    - multihash-cryptonite
    - base16-bytestring

  default-extensions:
    - OverloadedStrings
    - MultiWayIf
    - GADTSyntax

tests:
  spec:
    main:                Spec.hs
    source-dirs:
      - test
      - src
    #ghc-options:
    #- -threaded
    #- -rtsopts
    #- -with-rtsopts=-N
    dependencies:
      - megaparsec
      - containers
      - transformers
      - mtl
      - text
      - vector
      - unsafeperformst
      - hspec
      - QuickCheck
      - raw-strings-qq
      - bytestring
      - multibase
      - ipld-cid
      - serialise
      - cryptonite
      - multihash-cryptonite
      - base16-bytestring
    default-extensions:
      - OverloadedStrings
      - MultiWayIf
      - GADTSyntax
    other-modules:
      - Language.Bishop.Term
      - Language.Bishop.Parse
      - Language.Bishop.Eval
      - Spec.Parse

